version: 2
updates:
  # Maintain GitHub Actions (Checkouts, Setup-Python, etc.)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain Python tools used for testing and conversion
  - package-ecosystem: "pip"
    directory: "/third_party"
    schedule:
      interval: "weekly"
    versioning-strategy: increase-if-necessary
