name: Check TfLite Files

on:
  workflow_call:
    inputs:
      trigger-sha:
        required: true
        type: string
      pr-number:
        required: true
        type: string
      pr-body:
        required: true
        type: string
    secrets:
      tflm-bot-token:
        required: true

jobs:
  check_tflite_files:
    runs-on: ubuntu-latest
    name: Check PR Modifies TfLite Files
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.trigger-sha }}

      - name: Check Files
        if: ${{ !contains(inputs.pr-body, 'NO_CHECK_TFLITE_FILES=') }}
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ inputs.pr-number }}
          TFLM_BOT_TOKEN: ${{ secrets.tflm-bot-token }}
        run: tensorflow/lite/micro/tools/ci_build/check_tflite_files.sh
