name: Check PR has Bug
on:
  pull_request:
    types: [labeled]

jobs:
  find-bug-tag:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.body, 'BUG=') }}
    steps:
      - run: |
          echo "PR description requires a BUG= line with issue number."
          echo "See https://testing.googleblog.com/2017/09/code-health-providing-context-with.html for additional context"
          exit 1
