name: Check TfLite Files

on:
  workflow_call:
    inputs:
      trigger-sha:
        required: true
        type: string
      pr-number:
        required: true
        type: string
      pr-body:
        required: true
        type: string

jobs:
  check_tflite_files:
    runs-on: ubuntu-latest
    name: Check PR Modifies TfLite Files
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.trigger-sha }}
          fetch-depth: 0

      - name: Check Files
        if: ${{ !contains(inputs.pr-body, 'NO_CHECK_TFLITE_FILES=') }}
        run: tensorflow/lite/micro/tools/ci_build/check_tflite_files.sh
