name: CI

on:
  pull_request:
    types: [labeled]

jobs:
  arduino:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'ci:run')
    name: Makefile x86 tests
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          tensorflow/lite/micro/tools/ci_build/test_arduino.sh

  bazel_tests:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'ci:run')
    name: Bazel Tests
    steps:
      - uses: actions/checkout@v2
      - name: "Set up bazel"
        run: |
          sudo ci/install_bazel.sh
      - name: "Test"
        run: |
          tensorflow/lite/micro/tools/ci_build/test_bazel.sh

  cortex_m_tests:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'ci:run')
    name: Cortex-M tests
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          tensorflow/lite/micro/tools/ci_build/test_bluepill.sh
          tensorflow/lite/micro/tools/ci_build/test_cortex_m_corstone_300.sh
          tensorflow/lite/micro/tools/ci_build/test_cortex_m_generic.sh
          tensorflow/lite/micro/tools/ci_build/test_sparkfun.sh
          tensorflow/lite/micro/tools/ci_build/test_stm32f4.sh

  check_code_style:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'ci:run')
    name: Code Style
    steps:
      - uses: actions/checkout@v2
      - name: Check
        # TODO(#11): Update the docker image to be hosted via github packages.
        uses: docker://jpwithers/tflite-micro-tests
        with:
          args: /bin/sh -c "/opt/tflm/tensorflow/lite/micro/tools/ci_build/test_code_style.sh"

  project_generation:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'ci:run')
    name: Project generation
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          # TODO(b/184886633): the downloads should happen as part of the create_tflm_tree
          # script or should optinally not be required.
          make -f tensorflow/lite/micro/tools/make/Makefile third_party_downloads
          tensorflow/lite/micro/tools/ci_build/test_project_generation.sh

  x86_tests:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'ci:run')
    name: Makefile x86 tests
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          tensorflow/lite/micro/tools/ci_build/test_makefile.sh
          tensorflow/lite/micro/tools/ci_build/test_x86.sh

      # TODO(#13): Uncomment the lines below once we can appropriately change
      # labels from PRs created from forks.
      # - name: Remove ci:run Tag
      #   uses: actions/github-script@v3
      #   with:
      #     github-token: ${{secrets.GITHUB_TOKEN}}
      #     script: |
      #       github.issues.removeLabel({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         name: 'ci:run'
      #       })
