name: Run-Xtensa

# This is the entry point for xtensa.yml for scheduled and workflow_dispatch events. 


on:
  schedule:
    # 10am UTC is 3am or 4am PT depending on daylight savings.
    - cron: '0 10 * * *'

  # Allow manually triggering of the workflow.
  workflow_dispatch: {}

jobs:
  call-xtensa-presubmit-dispatched:
    uses: ./.github/workflows/xtensa_presubmit.yml
    if: |
      github.event_name == 'workflow_dispatch' 
    with:
      trigger-sha: ${{ github.sha }}
      is-dispatched: 'TRUE'
    secrets:
      tflm-bot-token: ${{ secrets.TFLM_BOT_PACKAGE_READ_TOKEN }}

  call-xtensa-postmerge-dispatched:
    uses: ./.github/workflows/xtensa_postmerge.yml
    if: |
      github.event_name == 'workflow_dispatch' 
    with:
      trigger-sha: ${{ github.sha }}
      is-dispatched: 'TRUE'
    secrets:
      tflm-bot-token: ${{ secrets.TFLM_BOT_PACKAGE_READ_TOKEN }}

  call-xtensa-presubmit-scheduled:
    uses: ./.github/workflows/xtensa_presubmit.yml
    if: |
      (github.event_name == 'schedule' && github.repository == 'tensorflow/tflite-micro')
    with:
      trigger-sha: ${{ github.sha }}
      is-scheduled: 'TRUE'
    secrets:
      tflm-bot-token: ${{ secrets.TFLM_BOT_PACKAGE_READ_TOKEN }}

  call-xtensa-postmerge-scheduled:
    uses: ./.github/workflows/xtensa_postmerge.yml
    if: |
      (github.event_name == 'schedule' && github.repository == 'tensorflow/tflite-micro')
    with:
      trigger-sha: ${{ github.sha }}
      is-scheduled: 'TRUE'
    secrets:
      tflm-bot-token: ${{ secrets.TFLM_BOT_PACKAGE_READ_TOKEN }}

  issue-on-error:
    needs: [call-xtensa-presubmit-scheduled,call-xtensa-postmerge-scheduled]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    uses: ./.github/workflows/issue_on_error.yml
    with:
      repo: ${{ github.repository }}
      workflow: ${{ github.workflow }}
      run_id: ${{ github.run_id }}
      run_number: ${{ github.run_number }}
      flag_label: ci:bot_issue
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}