
name: Sparkfun Edge

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
on:
  schedule:
    # 10am UTC is 3am or 4am PT depending on daylight savings.
    - cron: '0 10 * * *'

  # Allow manually triggering of the workflow.
  workflow_dispatch: {}

jobs:
  cortex_m_daily:
    runs-on: ubuntu-latest
    name: Cortex-M Continuous Builds
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          tensorflow/lite/micro/tools/ci_build/test_sparkfun.sh
