name: Suite - Cortex-M

on:
  workflow_call:
    inputs:
      trigger-sha:
        required: true
        type: string
    secrets:
      tflm-bot-token:
        required: true

jobs:
  # --- GCC Tests ---

  generic_gcc:
    runs-on: ubuntu-latest
    name: Cortex-M Generic (GCC)
    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.trigger-sha }}
      - name: Install dependencies
        run: |
          pip3 install Pillow
          pip3 install numpy
      - name: Test
        run: |
          tensorflow/lite/micro/tools/ci_build/test_cortex_m_generic.sh

  corstone_300_gcc:
    runs-on: ubuntu-latest
    name: Cortex-M Corstone 300 (GCC)
    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.trigger-sha }}
      - name: Install dependencies
        run: |
          pip3 install Pillow
          pip3 install numpy
      - name: Test
        run: |
          tensorflow/lite/micro/tools/ci_build/test_cortex_m_corstone_300.sh

  # --- Arm Clang Tests ---

  generic_armclang:
    runs-on: ubuntu-latest
    name: Cortex-M Generic (Arm Clang)
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.trigger-sha }}
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip3 install Pillow
          pip3 install numpy
      - name: Install Arm tools
        uses: ARM-software/cmsis-actions/vcpkg@v1
        with: 
          config: "tensorflow/lite/micro/tools/github/arm/vcpkg-configuration.json"
      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1
      - name: Test
        run: |
          tensorflow/lite/micro/tools/ci_build/test_cortex_m_generic.sh armclang

  corstone_300_armclang:
    runs-on: ubuntu-latest
    name: Cortex-M Corstone 300 (Arm Clang)
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.trigger-sha }}
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip3 install Pillow
          pip3 install numpy
      - name: Install Arm tools
        uses: ARM-software/cmsis-actions/vcpkg@v1
        with: 
          config: "tensorflow/lite/micro/tools/github/arm/vcpkg-configuration.json"
      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1
      - name: Test
        run: |
          tensorflow/lite/micro/tools/ci_build/test_cortex_m_corstone_300.sh armclang
      - uses: actions/upload-artifact@v6
        with:
          name: my-artifact
          path: |
            tensorflow/
            gen/