name: Test - Misc (Style, Project Gen)

on:
  workflow_call:
    inputs:
      trigger-sha:
        required: true
        type: string

jobs:
  check_code_style:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    name: Code Style
    container:
      image: ghcr.io/tflm-bot/tflm-ci:0.6.7
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.trigger-sha }}
      - name: Check
        run: tensorflow/lite/micro/tools/ci_build/test_code_style.sh

  cpp_build_warnings:
    runs-on: linux-x86-n2-16
    timeout-minutes: 60
    container:
      image: ghcr.io/tflm-bot/tflm-ci:0.6.7
    name: C++ Build Warnings
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.trigger-sha || github.ref }}
      - uses: bazel-contrib/setup-bazel@0.18.0
        with:
          bazelisk-cache: true
          disk-cache: true
          cache-save: ${{ github.event_name == 'push' }}
          repository-cache: true
      - name: Build with Warnings as Errors
        run: bazel build --copt="-Werror" //...

  project_generation:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    name: Project Generation
    container:
      image: ghcr.io/tflm-bot/tflm-ci:0.6.7
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.trigger-sha }}
      - uses: bazel-contrib/setup-bazel@0.18.0
        with:
          bazelisk-cache: true
          disk-cache: true
          cache-save: ${{ github.event_name == 'push' }}
          repository-cache: true
      - name: Test
        run: |
          cd ..
          tflite-micro/tensorflow/lite/micro/tools/ci_build/test_project_generation.sh tflite-micro/
