name: Test - Misc (Style, Project Gen)

on:
  workflow_call:
    inputs:
      trigger-sha:
        required: true
        type: string

jobs:
  check_code_style:
    runs-on: ubuntu-latest

    name: Code Style
    container:
      image: ghcr.io/tflm-bot/tflm-ci:0.6.6
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.trigger-sha }}
      - name: Check
        run: tensorflow/lite/micro/tools/ci_build/test_code_style.sh

  cpp_build_warnings:
    runs-on: ubuntu-latest

    name: C++ Build Warnings
    steps:
      - uses: jlumbroso/free-disk-space@v1.3.1
        with:
          android: true
          dotnet: true
          haskell: true
          docker-images: false
          large-packages: false
          tool-cache: false
          swap-storage: false    
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.trigger-sha }}
      - name: Build with Warnings as Errors
        uses: docker://ghcr.io/tflm-bot/tflm-ci:0.6.6
        with:
          args: bazel build --copt="-Werror" //...

  project_generation:
    runs-on: ubuntu-latest

    name: Project Generation
    container:
      image: ghcr.io/tflm-bot/tflm-ci:0.6.6
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.trigger-sha }}
      - name: Test
        run: |
          cd ..
          tflite-micro/tensorflow/lite/micro/tools/ci_build/test_project_generation.sh tflite-micro/
