# YAML schema for GitHub Actions:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
#
# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/
#
# This file can not be run stand-alone. It is called from tests_post.yml as part of
# the ci automation or from run_xtensa.yml for scheduled or manual dispatch.

name: Xtensa Postmerge

on:
  workflow_call:
    inputs:
      trigger-sha:
        required: true
        type: string
    secrets:
      tflm-bot-token:
        required: true

jobs:
  f1_unit_tests:
    runs-on: ubuntu-latest

    name: Fusion F1 Unit Tests (postmerge)
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.trigger-sha }}
      - run: |
          rm -rf .git
          echo ${{ secrets.tflm-bot-token }} | docker login ghcr.io -u tflm-bot --password-stdin
          docker run --env XTENSA_TOOLS_VERSION=RI-2020.4-linux --rm -v `pwd`:/opt/tflite-micro ghcr.io/tflm-bot/xtensa_xplorer_13:0.3 \
          /bin/bash -c \
          "cd /opt && tflite-micro/tensorflow/lite/micro/tools/ci_build/test_xtensa_fusion_f1.sh EXTERNAL tflite-micro/"

  vision_p6_unit_tests:
    runs-on: ubuntu-latest

    name: Vision P6 Unit Tests (postmerge)
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.trigger-sha }}
      - run: |
          rm -rf .git
          echo ${{ secrets.tflm-bot-token }} | docker login ghcr.io -u tflm-bot --password-stdin
          docker run --env XTENSA_TOOLS_VERSION=RI-2020.4-linux --rm -v `pwd`:/opt/tflite-micro ghcr.io/tflm-bot/xtensa_xplorer_13:0.3 \
          /bin/bash -c \
          "cd /opt && tflite-micro/tensorflow/lite/micro/tools/ci_build/test_xtensa_vision_p6.sh RUN_TESTS tflite-micro/"

  hifimini_unit_tests:
    runs-on: ubuntu-latest

    name: Hifimini Unit Tests (postmerge)
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.trigger-sha }}
      - run: |
          rm -rf .git
          echo ${{ secrets.tflm-bot-token }} | docker login ghcr.io -u tflm-bot --password-stdin
          docker run --env XTENSA_TOOLS_VERSION=RI-2019.2-linux --rm -v `pwd`:/opt/tflite-micro ghcr.io/tflm-bot/xtensa_xplorer_11:0.2 \
          /bin/bash -c \
          "cd /opt && tflite-micro/tensorflow/lite/micro/tools/ci_build/test_xtensa_hifimini.sh tflite-micro/"
